// STAT
export const STAT_REQUEST = 'STAT_REQUEST';
export const STAT_SUCCESS = 'STAT_SUCCESS';
export const STAT_FAILURE = 'STAT_FAILURE';
export const STAT_UPDATE = 'STAT_UPDATE';

// CUSTOM LEVELS
export const CUSTOM_LEVELS_REQUEST = 'CUSTOM_LEVELS_REQUEST';
export const CUSTOM_LEVELS_SUCCESS = 'CUSTOM_LEVELS_SUCCESS';
export const CUSTOM_LEVELS_FAILURE = 'CUSTOM_LEVELS_FAILURE';
export const CUSTOM_LEVELS_UPDATE = 'CUSTOM_LEVELS_UPDATE';
export const CUSTOM_LEVELS_ADD = 'CUSTOM_LEVELS_ADD';
export const CUSTOM_LEVELS_REMOVE = 'CUSTOM_LEVELS_REMOVE';

// PARAMETERS
export const PARAMETERS_REQUEST = 'PARAMETERS_REQUEST';
export const PARAMETERS_SUCCESS = 'PARAMETERS_SUCCESS';
export const PARAMETERS_FAILURE = 'PARAMETERS_FAILURE';
export const PARAMETERS_UPDATE = 'PARAMETERS_UPDATE';

// THRESHOLDS
export const THRESHOLDS_REQUEST = 'THRESHOLDS_REQUEST';
export const THRESHOLDS_SUCCESS = 'THRESHOLDS_SUCCESS';
export const THRESHOLDS_FAILURE = 'THRESHOLDS_FAILURE';
export const THRESHOLDS_UPDATE = 'THRESHOLDS_UPDATE';
export const THRESHOLDS_UPDATE_ALERT = 'THRESHOLDS_UPDATE_ALERT';

// CHART
export const CHART_REQUEST = 'CHART_REQUEST';
export const CHART_SUCCESS = 'CHART_SUCCESS';
export const CHART_FAILURE = 'CHART_FAILURE';
export const CHART_UPDATE = 'CHART_UPDATE';

// WEBSOCKET
export const  WS_CONNECT = 'WS_CONNECT';
export const  WS_CONNECTING = 'WS_CONNECTING';
export const  WS_CONNECTED = 'WS_CONNECTED';
export const  WS_DISCONNECT = 'WS_DISCONNECT';
export const  WS_DISCONNECTED = 'WS_DISCONNECTED';
export const  WS_ERROR = 'WS_ERROR';
export const  WS_MESSAGE = 'WS_MESSAGE';
